name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

     steps:
    - uses: actions/checkout@v2
    - name: Build
      run:  cd Cuddly
          xcodebuild clean test -project Cuddly.xcodeproj -scheme ProjectName -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          swift build -v
    - name: Run tests
      run: cd Cuddly
           swift test -v
